import { FilterTypes } from '@core/types'
import { useSales } from 'context/SalesContext'
import Head from 'next/head'

export default function Home() {
  const { getSales, getSalesBy } = useSales()

  const handleClickSales = () => {
    console.log(getSalesBy(FilterTypes.WEEK))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleClickSales}>getSalesBy</button>
    </div>
  )
}
